name: tallyTool
version: '${version}'

main: dev.ozpyn.tallyTool.TallyTool
api-version: '26.1'

commands:
  itemtally:
    description: Scan a region and count all items in inventories.
    usage: /itemtally <x1> <y1> <z1> <x2> <y2> <z2>
    permission: tallytool.itemtally

permissions:
  tallytool.itemtally:
    default: op